#!/usr/bin/env node
/**
 * FarmscapeOS — Farm Init Utility
 *
 * Interactive CLI to generate a farm configuration file.
 * Usage: pnpm run init
 */
import { createInterface } from 'readline';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const configPath = resolve(__dirname, '../src/farms/local.config.ts');

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

async function main() {
  console.log('\n🌱 FarmscapeOS — New Farm Setup\n');

  if (existsSync(configPath)) {
    const overwrite = await ask('  src/farms/local.config.ts already exists. Overwrite? (y/N) ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('  Aborted.\n');
      rl.close();
      return;
    }
  }

  const name = (await ask('  Farm name: ')) || 'My Farm';
  const subtitle = (await ask('  Subtitle (optional): ')) || '';
  const address = (await ask('  Address (optional): ')) || '';
  const unitInput = (await ask('  Unit system — ft or m (default: ft): ')) || 'ft';
  const unit = unitInput === 'm' ? 'm' : 'ft';

  console.log('\n  Define your property boundary as corner coordinates.');
  console.log('  Pick one corner as (0,0) and measure others relative to it.');
  console.log('  Enter corners as "x,y,label" — one per line. Empty line to finish.\n');

  const boundary = [];
  let i = 1;
  while (true) {
    const line = await ask(`  Corner ${i} (x,y,label): `);
    if (!line.trim()) break;
    const parts = line.split(',').map((s) => s.trim());
    const x = parseFloat(parts[0]) || 0;
    const y = parseFloat(parts[1]) || 0;
    const label = parts[2] || `Corner ${i}`;
    boundary.push({ x, y, label });
    i++;
  }

  if (boundary.length < 3) {
    console.log('  Using default rectangular boundary (200x300).');
    boundary.length = 0;
    boundary.push(
      { x: 0, y: 0, label: 'SW Corner' },
      { x: 200, y: 0, label: 'SE Corner' },
      { x: 200, y: 300, label: 'NE Corner' },
      { x: 0, y: 300, label: 'NW Corner' },
    );
  }

  // Calculate center and size from boundary
  const xs = boundary.map((p) => p.x);
  const ys = boundary.map((p) => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);
  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2;
  const width = (maxX - minX) * 1.5;
  const depth = (maxY - minY) * 1.5;

  const donationUrl = await ask('  Donation URL for your farm (optional): ');
  const donationLabel = donationUrl ? (await ask('  Donation button label (optional): ')) : '';

  const boundaryStr = boundary
    .map((p) => `    { x: ${p.x}, y: ${p.y}, label: '${p.label}' },`)
    .join('\n');

  const donationBlock = donationUrl
    ? `
  donation: {
    farmUrl: '${donationUrl}',
    farmLabel: '${donationLabel || `Support ${name}`}',
    upstreamPercent: 5,
    upstreamUrl: 'https://github.com/sponsors/sahrens',
  },`
    : `
  donation: {
    upstreamPercent: 5,
    upstreamUrl: 'https://github.com/sponsors/sahrens',
  },`;

  const config = `/**
 * ${name} — Farm Configuration
 * Generated by: pnpm run init
 */
import type { FarmConfig } from '../farm.config.types';

const farm: FarmConfig = {
  name: '${name}',${subtitle ? `\n  subtitle: '${subtitle}',` : ''}${address ? `\n  address: '${address}',` : ''}

  unit: '${unit}',
  unitLabel: '${unit}',

  boundary: [
${boundaryStr}
  ],

  overlays: [],

  camera: {
    position: [${Math.round(centerX)}, ${Math.round(depth * 0.4)}, ${Math.round(centerX)}],
    target: [${Math.round(centerX)}, 0, ${Math.round(-centerY)}],
    far: ${Math.round(depth * 3)},
  },

  ground: {
    center: [${Math.round(centerX)}, ${Math.round(-centerY)}],
    size: [${Math.round(width)}, ${Math.round(depth)}],
  },

  colors: {},
  subtypeLabels: {},
${donationBlock}
};

export default farm;
`;

  writeFileSync(configPath, config);
  console.log(`\n  ✅ Created src/farms/local.config.ts`);
  console.log(`\n  Next steps:`);
  console.log(`    1. Review and edit src/farms/local.config.ts`);
  console.log(`    2. Set up your database: see README for D1 setup`);
  console.log(`    3. Build and deploy: pnpm build && wrangler deploy`);
  console.log('');

  rl.close();
}

main().catch((err) => {
  console.error(err);
  rl.close();
  process.exit(1);
});
